default: &default
  password: <%= ENV['REDIS_PASSWORD'] || '' %>
  <% if ENV['REDIS_SENTINELS'].present? %>
  sentinel_url: <%= ENV['REDIS_SENTINEL_URL'] || '' %>
  sentinels:
  <% JSON.parse(ENV['REDIS_SENTINELS']).each do |items| %>
    - host: <%= items['host'] %>
      port: <%= items['port'] %>
  <% end %>
  <% else %>
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['REDIS_PORT'] || '6379' %>
  <% end %>

test:
  <<: *default
  namespace: 'kaiju:test'

development:
  <<: *default
  namespace: 'kaiju:dev'
  
production:
  <<: *default
  namespace: 'kaiju:prod'
  ssl: <%= ENV['REDIS_USE_SSL'] || 'false' %>